apiVersion: apps/v1
kind: Deployment
metadata:
  name: "connectivity-proxy-operator"
spec:
  selector:
    matchLabels:
      app: "connectivity-proxy-operator"
  template:
    metadata:
      labels:
        app: "connectivity-proxy-operator"
    spec:
      serviceAccountName: "connectivity-proxy-operator"
      imagePullSecrets:
      - name: "docker-pull-secret"
      containers:
      - name: "connectivity-proxy-operator"
        image: "connectivity.common.repositories.cloud.sap/chuchulski/test-proxy-operator:test"
        imagePullPolicy: "Always"
        env:
        - name: START_APPLICATION
          value: "proxy-operator"
        resources:
          requests:
            cpu: "100m"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "1024M"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 3

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: "connectivity-proxy-operator"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "connectivity-proxy-operator-rbac"
rules:
# CRD definitions
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
# Connectivity Proxy custom resource
- apiGroups: ["connectivityproxy.sap.com"]
  resources: ["connectivityproxies", "connectivityproxies/status"]
  verbs: ["*"]
# main workload resources
- apiGroups: [""]
  resources: ["deployments", "statefulsets", "services", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "services", "configmaps", "secrets"]
  verbs: ["*"]
# PriorityClass
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["*"]
# ServiceAccounts
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["*"]
# RBAC resources
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "clusterroles", "rolebindings", "clusterrolebindings"]
  verbs: ["*"]
# Istio resources
- apiGroups: ["networking.istio.io"]
  resources: ["gateways", "virtualservices", "destinationrules"]
  verbs: ["*"]
- apiGroups: ["security.istio.io"]
  resources: ["peerauthentications"]
  verbs: ["*"]
# SM resources
- apiGroups: ["connectivityproxy.sap.com"]
  resources: ["servicemappings", "servicemappings/status"]
  verbs: ["*"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["*"]
# SAP BTP Operator resources
- apiGroups: ["services.cloud.sap.com"]
  resources: ["serviceinstances", "servicebindings"]
  verbs: ["*"]
# Gardener Cert Management resources
- apiGroups: ["cert.gardener.cloud"]
  resources: ["certificates"]
  verbs: ["*"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "connectivity-proxy-operator-rbac"
subjects:
- kind: ServiceAccount
  name: "connectivity-proxy-operator"
  namespace: "apps" # beware: this has to be aligned with the namespace of the Deployment of the Operator and the ServiceAccount
roleRef:
  kind: ClusterRole
  name: "connectivity-proxy-operator-rbac"
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: connectivityproxies.connectivityproxy.sap.com
spec:
  group: connectivityproxy.sap.com
  names:
    kind: ConnectivityProxy
    plural: connectivityproxies
    shortNames:
    - cp
    singular: connectivityproxy
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.state
      name: STATE
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              config:
                properties:
                  integration:
                    properties:
                      auditlog:
                        properties:
                          mode:
                            pattern: ^(console|service)$
                            type: string
                          serviceCredentialsKey:
                            type: string
                        required:
                        - mode
                        type: object
                      connectivityService:
                        properties:
                          serviceCredentialsKey:
                            type: string
                        required:
                        - serviceCredentialsKey
                        type: object
                    required:
                    - auditlog
                    - connectivityService
                    type: object
                  servers:
                    properties:
                      businessDataTunnel:
                        properties:
                          externalHost:
                            type: string
                          externalPort:
                            maximum: 65535.0
                            minimum: 1.0
                            type: integer
                        required:
                        - externalHost
                        - externalPort
                        type: object
                      proxy:
                        properties:
                          authorization:
                            properties:
                              oauth:
                                properties:
                                  allowedClientId:
                                    type: string
                                required:
                                - allowedClientId
                                type: object
                            required:
                            - oauth
                            type: object
                          http:
                            properties:
                              enabled:
                                type: boolean
                              allowRemoteConnections:
                                type: boolean
                              enableProxyAuthorization:
                                type: boolean
                              port:
                                maximum: 65535.0
                                minimum: 1.0
                                type: integer
                            type: object
                          rfcAndLdap:
                            properties:
                              enabled:
                                type: boolean
                              allowRemoteConnections:
                                type: boolean
                              enableProxyAuthorization:
                                type: boolean
                              port:
                                maximum: 65535.0
                                minimum: 1.0
                                type: integer
                            type: object
                          socks5:
                            properties:
                              enabled:
                                type: boolean
                              allowRemoteConnections:
                                type: boolean
                              enableProxyAuthorization:
                                type: boolean
                              port:
                                maximum: 65535.0
                                minimum: 1.0
                                type: integer
                            type: object
                        type: object
                    required:
                    - businessDataTunnel
                    - proxy
                    type: object
                  subaccountId:
                    pattern: "^[a-zA-Z0-9-]+$"
                    type: string
                  subaccountSubdomain:
                    type: string
                  tenantMode:
                    pattern: ^(dedicated|shared)$
                    type: string
                  serviceChannels:
                    properties:
                      enabled:
                        type: boolean
                    required:
                    - enabled
                    type: object
                  multiRegionMode:
                    properties:
                      enabled:
                        type: boolean
                      configMapName:
                        type: string
                    required:
                    - enabled
                    type: object
                  highAvailabilityMode:
                    pattern: ^(off|path|subdomain)$
                    type: string
                required:
                - integration
                - servers
                - tenantMode
                type: object
              deployment:
                properties:
                  image:
                    properties:
                      registry:
                        type: string
                      repository:
                        type: string
                      tag:
                        type: string
                      digest:
                        type: string
                      pullPolicy:
                        pattern: ^(Always|IfNotPresent|Never)$
                        type: string
                      pullSecret:
                        type: string
                    required:
                    - registry
                    - repository
                    - tag
                    type: object
                  utilityImage:
                    properties:
                      registry:
                        type: string
                      repository:
                        type: string
                      tag:
                        type: string
                      digest:
                        type: string
                      pullPolicy:
                        pattern: ^(Always|IfNotPresent|Never)$
                        type: string
                      pullSecret:
                        type: string
                    required:
                    - registry
                    - repository
                    - tag
                    type: object
                  replicaCount:
                    minimum: 1.0
                    type: integer
                  resources:
                    properties:
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        required:
                        - cpu
                        - memory
                        type: object
                      maxFileDescriptorCount:
                        minimum: 10.0
                        type: integer
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        required:
                        - cpu
                        - memory
                        type: object
                    required:
                    - maxFileDescriptorCount
                    - limits
                    type: object
                  nodeSelector:
                    additionalProperties:
                      type: string
                    type: object
                  restartWatcher:
                    properties:
                      enabled:
                        type: boolean
                    required:
                    - enabled
                    type: object
                required:
                - image
                - utilityImage
                - replicaCount
                - resources
                type: object
              ingress:
                properties:
                  className:
                    pattern: ^(nginx|istio)$
                    type: string
                  tls:
                    properties:
                      secretName:
                        type: string
                    required:
                    - secretName
                    type: object
                  timeouts:
                    properties:
                      proxy:
                        properties:
                          connect:
                            type: integer
                          read:
                            type: integer
                          send:
                            type: integer
                        required:
                        - connect
                        - read
                        - send
                        type: object
                    type: object
                  istio:
                    properties:
                      namespace:
                        type: string
                      gateway:
                        properties:
                          selector:
                            additionalProperties:
                              type: string
                            type: object
                        type: object
                      tls:
                        properties:
                          ciphers:
                            items:
                              type: string
                            type: array
                        type: object
                    type: object
                  annotations:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - timeouts
                type: object
              secretConfig:
                properties:
                  integration:
                    properties:
                      connectivityService:
                        properties:
                          secretName:
                            type: string
                          secretData:
                            pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{4})$"
                            type: string
                        required:
                        - secretName
                        type: object
                      auditlogService:
                        properties:
                          secretName:
                            type: string
                          secretData:
                            pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{4})$"
                            type: string
                        required:
                        - secretName
                        type: object
                    required:
                    - connectivityService
                    type: object
                required:
                - integration
                type: object
            required:
            - config
            - deployment
            - ingress
            - secretConfig
            type: object
          status:
            properties:
              state:
                type: string
              observedGeneration:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
